<?php

/**
 * Add each role as a submenu item for the 'permissions' item
 * in the admin_menu.
 */
function caftools_menu() {

  if (module_exists('admin_menu')) {
    $items = array();
    $roles = user_roles();

    foreach($roles as $rid => $role) {
      $items['admin/user/permissions/edit/' . $rid] = array(
        'title' => $role,
        'description' => 'Determine access to features by selecting permissions for ' . $role . '.',
        'page callback' => 'overrides_user_admin_perm_redir',
        'page arguments' => array(4),
        'access callback' => 'user_access',
        'access arguments' => array('administer permissions'),
      );
    }
    return $items;
  }
}

/**
 * Helper to redirect the user to the correct role based
 * permissions admin page.
 */
function caftools_user_admin_perm_redir($rid) {
  drupal_goto('admin/user/permissions/'. $rid);
}
